// syntax定义.proto使用的版本
// 一个文件只能出现一次
syntax = "proto3";
// option可以多个，这里申明的golang的
// 一个文件只能出现一次
option go_package = "./pb_user";
// 类似于命名空间：这里是包名
// 一个文件只能出现一次
package user;
// 申明服务接口
service UserService {
    // 这个是固定写法，规定函数请求值以及返回值
    rpc GetUser(GetUserRequest) returns (GetUserResponse);
}
// message规定请求类型
message GetUserRequest {
    // 这里是1是一个标识位置，用于传递，并不是赋值
    string user_id = 1;
    double a = 2;
    double b = 3;
}
// message规定的响应类型
message GetUserResponse {
    string user_id = 1;
    string nickname = 2;
    double sum = 3;
}
// 编译命令
// --go_out=. 表示生成 go 文件到当前目录,这里是 ./pb_user
// --go-grpc_out=. 表示生成 grpc 文件到当前目录,这里是 ./pb_user
// --proto_path=. 表示 proto 文件路径,这里是 .
// protoc --go_out=. --go-grpc_out=. --proto_path=. user.proto